create table member
(
    id               bigint generated by default as identity,
    sign_in_id       varchar(30),
    sign_in_password varchar(150),
    membership_code  varchar(8),
    email            varchar(30),
    phone_number     varchar(15),
    member_status    varchar(10),
    primary key (id)
);
