server:
  port: 8080

spring:
  application:
    name: kttr-api

  redis:
    redisson:
      config: | 
        singleServerConfig:
          address: redis://localhost:60
          username: kttr-server
          password: kttr!@#
          connectionPoolSize: 100
          connectionMinimumIdleSize: 100
          connectionPoolSize: 100
          tcpNoDelay: true
        maxCleanUpDelay: 30

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
    db_close_delay: -1

#database:
#  type: com.zaxxer.hikari.HikariDataSource
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://db-frvbp-kr.vpc-pub-cdb.ntruss.com:3306/kttr?useSSL=false
#  username: kttr_service
#  password: KttrService1!
#  hikari:
#    poolName: Hikari
#    auto-commit: false