server:
  port: 8080

spring:
  application:
    name: kttr-api

  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: none

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#    database-platform: org.hibernate.dialect.H2Dialect
database:
  type: com.zaxxer.hikari.HikariDataSource
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://db-frvbp-kr.vpc-pub-cdb.ntruss.com:3306/kttr?useSSL=false
  username: kttr_service
  password: KttrService1!
  hikari:
    poolName: Hikari
    auto-commit: false

